name: Deploy Node Application

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest  # This runs on GitHub-hosted Ubuntu
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub 
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker Image
        run: docker build -t parzival2808/xmretail:latest .

      - name: Push Image to Docker Hub
        run: docker push parzival2808/xmretail:latest

  deploy:
    needs: build
    runs-on: [self-hosted, linux]  # ✅ Change this to target your Debian runner
    steps:
      - name: Ensure Docker is Running (for Debian)
        run: sudo systemctl start docker

      - name: Pull Latest Docker Image
        run: docker pull parzival2808/xmretail:latest
      
      - name: Stop Existing Container (if running)
        run: docker rm -f xmretail-app-container || true
      
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name xmretail-app-container \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            parzival2808/xmretail:latest
