name: Delpoy Node Application

on:
 push:
   branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker IMage
        run : docker build -t parzival2808/xmretail .
      - name: Publish Image to Docker hub
        run: docker push parzival2808/xmretail:latest
    

  deploy: 
    needs: build 
    runs-on: self-hosted
    steps:
       - name: pull Image from Docker hub
         run : docker pull parzival2808/xmretail:latest
       - name: Run Docker Container
         run : docker run -d -p 4000:4000 --name xmretail-app-container -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}'
